### ISSUE TITLE
Auto format the file on the save using !v fmt

### ISSUE THREAD

**Issue by mattsoftware** [ollykel/v-vim#15]
Using plugins like Prettier on javascript files, when a file is saved in vim the prettier command will get run over the file and the contents updated according to prettier's formatting rules.

I notice the same is available for v, in the v's binary as an option.

Would it be in the scope of this plugin to detect if the v binary is in the path (or perhaps an option to point to the v binary) and run `v fmt` over the contents on save?

**Comment by ollykel** [comment]
Certainly! It shouldn't be hard to implement at all, I'll have it done by the end of the weekend!

In the meantime, you can run ":%!v fmt -" to format your code at any point while you're programming.

Cheers!

**Comment by ollykel** [comment]
Implemented by #16 . You can now enable automatic file formatting via g:v_autofmt_bufwritepre = 1 or b:v_autofmt_bufwritepre = 1.

**Comment by mattsoftware** [comment]
Perfect, works well, thanks for jumping on it so quickly :)

**Comment by ollykel** [comment]
Update: pr #16 was an unsafe implementation of _VFormatFile, as it did not check whether vfmt had returned an error before altering the buffer. This could result in the contents of the buffer being replaced with an error message, which will be particularly troublesome if you write to file using :x, :wq, or ZZ. I apologize for my carelessness.

Pr #17 implements _VFormatFile safely by checking whether vfmt returned an error before altering the buffer. I urge you and anyone else who has installed the plugin in the past day to reinstall it immediately.

Once again, I apologize for the inconvenience.
